export type VideoCategory = 'talk' | 'panel' | 'explainer' | 'clip'

export interface Video {
  id: string
  slug: string
  title: string
  description: string
  youtubeVideoId: string
  date: string
  duration?: string
  category?: VideoCategory
  tags?: string[]
  thumbnailUrl?: string            // override auto-generated YouTube thumbnail if needed
  thumbnailPosition?: string       // CSS objectPosition for thumbnailUrl, e.g. 'center 20%'
}

// ─── Video library ────────────────────────────────────────────────────────────
// To add a video, copy the YouTube URL (youtube.com/watch?v=XXXXXXXXXXX),
// take the ID after ?v= and paste it as youtubeVideoId.
// Thumbnail is auto-generated from YouTube; set thumbnailUrl to override.

export const videos: Video[] = [
  {
    id: '1',
    slug: 'digital-health-ai-hot-takes-3',
    title: 'Digital health and AI in healthcare hot takes #3',
    description: 'The third instalment of unfiltered hot takes on AI and digital health,what is working, what is hype, and what the field needs to hear.',
    youtubeVideoId: 'cNWBR8WWbh8',
    date: 'Mar 2026',
    category: 'clip',
    tags: ['AI', 'Digital Health', 'Hot Takes'],
  },
  {
    id: '2',
    slug: 'digital-innovation-in-humanitarian-settings',
    title: 'Digital innovation in humanitarian settings',
    description: 'How does an organisation like the ICRC - working in conflict zones, disasters, and last-mile settings - approach digital transformation? Javier Elkin spent three years building the ICRC\'s digital health unit from scratch, covering prioritisation frameworks, DHIS2 implementation, and the MOOVE/Medotron initiative to validate LLMs for humanitarian settings.',
    youtubeVideoId: 'LjbXiGTCtDs',
    date: 'Feb 2026',
    category: 'talk',
    tags: ['Humanitarian Health', 'AI', 'Implementation', 'Open Source', 'LLMs', 'ICRC'],
  },
  {
    id: '3',
    slug: 'usaid-cuts-womens-health-leading-the-right-way',
    title: 'USAID cuts, women\'s health and leading the right way',
    description: 'A direct conversation about the impact of USAID funding cuts on women\'s health programmes globally, and what principled leadership looks like when the landscape shifts rapidly.',
    youtubeVideoId: 'eCvmUpHF2Kc',
    date: 'Feb 2026',
    category: 'talk',
    tags: ['USAID', 'Women\'s Health', 'Global Health', 'Funding', 'Leadership'],
  },
  {
    id: '4',
    slug: 'why-displaced-people-need-a-digital-identity',
    title: 'Why displaced people need a digital identity',
    description: 'Without a digital identity, displaced people cannot access healthcare, financial services, or legal protection. This talk explores why digital identity is foundational infrastructure for refugee and migrant health.',
    youtubeVideoId: '3UYzwcr3h4M',
    date: 'Feb 2026',
    category: 'talk',
    tags: ['Digital Identity', 'Refugees', 'Displaced People', 'Global Health'],
  },
  {
    id: '5',
    slug: 'digital-health-ai-hot-takes-2',
    title: 'Digital health and AI in healthcare hot takes #2',
    description: 'More unfiltered takes on the state of AI and digital health,from the overhyped to the genuinely transformative.',
    youtubeVideoId: 'F35stSXcm_A',
    date: 'Jan 2026',
    category: 'clip',
    tags: ['AI', 'Digital Health', 'Hot Takes'],
  },
  {
    id: '6',
    slug: 'digital-health-ai-hot-takes-1',
    title: 'Digital health and AI in healthcare hot takes #1',
    description: 'The first in a series of sharp, direct takes on AI and digital health,cutting through the noise to what actually matters.',
    youtubeVideoId: 'DBEklHTuGgY',
    date: 'Jan 2026',
    category: 'clip',
    tags: ['AI', 'Digital Health', 'Hot Takes'],
  },
  {
    id: '7',
    slug: 'evaluation-level-up-measuring-what-matters',
    title: 'Evaluation Level Up: Measuring what matters',
    description: 'A practical guide to levelling up how digital health programmes are evaluated,moving beyond vanity metrics toward evidence that actually drives decisions and funding.',
    youtubeVideoId: 'hINV05lq86E',
    date: 'Nov 2025',
    category: 'talk',
    tags: ['Evaluation', 'Evidence', 'Implementation', 'Digital Health'],
  },
  {
    id: '8',
    slug: 'social-impact-scarcity-power-of-community',
    title: 'Social impact in a time of scarcity, and the power of community',
    description: 'How do organisations sustain social impact when resources are scarce? This conversation explores community-led approaches and what it means to build resilience into health programmes.',
    youtubeVideoId: 'yazW6eG90pA',
    date: 'Oct 2025',
    category: 'talk',
    tags: ['Social Impact', 'Community Health', 'Sustainability', 'Global Health'],
  },
  {
    id: '9',
    slug: 'digital-health-innovation-with-refugee-communities',
    title: 'Digital health innovation with refugee communities: a founder\'s story',
    description: 'A founder\'s first-hand account of building digital health tools with and for refugee communities,the challenges, the pivots, and what it actually takes to do this work with integrity.',
    youtubeVideoId: 'l_p3zJGFKf0',
    date: 'Oct 2025',
    category: 'talk',
    tags: ['Refugees', 'Founders', 'Digital Health', 'Innovation'],
  },
  {
    id: '10',
    slug: 'quick-insight-evidence-comms-digital-health',
    title: 'Quick insight: How to level up your evidence comms in digital health',
    description: 'A short, practical guide to communicating evidence more effectively in digital health,what funders, policy makers, and implementers actually want to see.',
    youtubeVideoId: 'WD_yEFQKeqs',
    date: 'Aug 2025',
    category: 'clip',
    tags: ['Evidence', 'Communications', 'Digital Health', 'Policy'],
  },
  {
    id: '11',
    slug: 'evolving-beyond-verticals-funding-what-matters',
    title: 'Evolving beyond verticals and funding what matters in healthcare',
    description: 'Why the siloed, disease-specific model of global health funding is holding back progress,and what a systems-oriented approach to investment could look like instead.',
    youtubeVideoId: 'oDM7POW_tZg',
    date: 'Aug 2025',
    category: 'talk',
    tags: ['Funding', 'Global Health', 'Systems Thinking', 'Policy'],
  },
  {
    id: '12',
    slug: 'healthtech-comms-storytelling-james-somauroo',
    title: 'Healthtech comms: communicating your impact with great storytelling',
    description: 'James Somauroo of SomX on why most digital health organisations communicate badly, how great storytelling changes that, and the frameworks that actually work for impact-driven brands.',
    youtubeVideoId: 'DMEe7Z6uPh0',
    date: 'Jul 2025',
    category: 'talk',
    tags: ['Communications', 'Storytelling', 'Founders', 'Digital Health'],
  },
  {
    id: '13',
    slug: 'hlth-europe-2025-local-ownership-malawi',
    title: 'HLTH Europe 2025 spotlight: Local ownership lessons from Malawi',
    description: 'A spotlight conversation from HLTH Europe 2025 on what genuine local ownership looks like in digital health,drawing on hard-won lessons from implementation in Malawi.',
    youtubeVideoId: '6iENQaQJGSg',
    date: 'Jul 2025',
    category: 'panel',
    tags: ['HLTH Europe', 'Malawi', 'Local Ownership', 'Implementation', 'Africa'],
  },
  {
    id: '14',
    slug: 'hlth-europe-2025-remidio-india-to-europe',
    title: 'HLTH Europe 2025 spotlight: Remidio,scaling from India to Europe and the US',
    description: 'A spotlight conversation from HLTH Europe 2025 with Remidio on the journey of scaling an AI-powered ophthalmology device from India to global markets,and what that path reveals about regulation, evidence, and market access.',
    youtubeVideoId: '6yY1LGWX60M',
    date: 'Jul 2025',
    category: 'panel',
    tags: ['HLTH Europe', 'India', 'AI', 'Medical Devices', 'Scale'],
  },
  {
    id: '15',
    slug: 'who-digital-director-alain-labrique',
    title: 'How the World Health Organization is evolving, with WHO Digital Director Alain Labrique',
    description: 'Alain Labrique, Director of Digital Health and Innovation at WHO, on how the organisation is navigating digital transformation, AI governance, and its role in shaping global digital health norms.',
    youtubeVideoId: 'i_39E8GfSfQ',
    date: 'Jul 2025',
    category: 'talk',
    tags: ['WHO', 'Policy', 'AI Governance', 'Digital Health', 'Global Health'],
  },
  {
    id: '16',
    slug: 'implementation-101-how-to-fail-well',
    title: 'Implementation 101 and how to fail well',
    description: 'A grounded look at the realities of implementing digital health in low-resource settings,including the failure modes nobody talks about and what it actually means to learn from them.',
    youtubeVideoId: 'I_3rIpaZ5NM',
    date: 'Jun 2025',
    category: 'talk',
    tags: ['Implementation', 'Failure', 'Digital Health', 'Learning'],
  },
  {
    id: '17',
    slug: 'africa-moment-healthtech-vc-case',
    title: 'From crisis to revolution: why Africa\'s moment is now,a healthtech VC\'s case',
    description: 'A venture capital perspective on why the confluence of mobile penetration, young demographics, and healthcare need makes Africa the most compelling opportunity in global healthtech right now.',
    youtubeVideoId: 'o5l_T-6AYd0',
    date: 'May 2025',
    category: 'talk',
    tags: ['Africa', 'Venture Capital', 'Investment', 'Healthtech'],
  },
  {
    id: '18',
    slug: 'regulatory-strategy-founders-policy-makers',
    title: 'Regulatory strategy for founders and policy makers',
    description: 'Demystifying the regulatory landscape for digital health,how founders should think about regulatory strategy early, and what policy makers need to understand about the tools they are overseeing.',
    youtubeVideoId: 'fFrQTWPHwW0',
    date: 'May 2025',
    category: 'talk',
    tags: ['Regulation', 'Policy', 'Founders', 'Digital Health'],
  },
  {
    id: '19',
    slug: 'health-first-innovation-second',
    title: 'Health First, Innovation Second',
    description: 'A provocative argument for recentering health outcomes,not technological novelty,as the primary metric for digital health success. What changes when you genuinely put health first?',
    youtubeVideoId: 'p7f7IOKL1_I',
    date: 'May 2025',
    category: 'talk',
    tags: ['Digital Health', 'Innovation', 'Health Outcomes', 'Systems Thinking'],
  },
  {
    id: '20',
    slug: 'digital-mental-health-research-lucy-cesnakova-dime',
    title: 'Digital mental health research insights with Lucy Cesnakova from DiME',
    description: 'Lucy Cesnakova from the Digital Medicine Society (DiME) shares research insights on digital mental health,what the evidence says, where the gaps are, and how researchers are navigating a fast-moving space.',
    youtubeVideoId: '4Z46Y1GRSP0',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['Mental Health', 'Research', 'Digital Health', 'Evidence'],
  },
  {
    id: '21',
    slug: 'making-ethics-actionable-jess-morley',
    title: 'Making ethics actionable in digital health with Jess Morley',
    description: 'Jess Morley on moving beyond ethics washing,how to embed genuine ethical reasoning into the design, deployment, and governance of digital health tools, particularly those using AI.',
    youtubeVideoId: '8ykoxDSM75g',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['Ethics', 'AI', 'Governance', 'Digital Health'],
  },
  {
    id: '22',
    slug: 'policy-insights-rwanda-ministry-health-find',
    title: 'Policy insights from the Rwanda Ministry of Health and FIND',
    description: 'A conversation at the intersection of national digital health policy and diagnostic innovation,drawing on Rwanda\'s experience as one of Africa\'s most ambitious digital health implementers.',
    youtubeVideoId: '8nm7bsPiFFI',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['Rwanda', 'Policy', 'Africa', 'Diagnostics', 'Digital Health'],
  },
  {
    id: '23',
    slug: 'co-designing-mental-health-solutions-young-people-rwanda',
    title: 'Co-designing mental health solutions with young people in Rwanda',
    description: 'What does genuine co-design look like when building digital mental health tools with young people in Rwanda? This conversation explores methodology, power dynamics, and what it means to design with,not for.',
    youtubeVideoId: 'uLrvo7B9kRE',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['Mental Health', 'Co-design', 'Rwanda', 'Young People', 'Africa'],
  },
  {
    id: '24',
    slug: 'supporting-rural-healthcare-india-technology',
    title: 'Supporting rural healthcare in India with technology',
    description: 'How technology is being deployed to reach rural and last-mile communities in India,the infrastructure challenges, the human factors, and the solutions that are actually working at scale.',
    youtubeVideoId: '0nGVpY5Mtwo',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['India', 'Rural Health', 'Last Mile', 'Digital Health', 'Asia'],
  },
  {
    id: '25',
    slug: 'digital-health-transformation-eswatini',
    title: 'Impactful digital health transformation through a clear vision and values: insights from Eswatini',
    description: 'Lessons from Eswatini\'s digital health transformation journey,how a clear national vision and grounded values shaped the choices made, the partnerships formed, and the outcomes achieved.',
    youtubeVideoId: 'khTl5Aal7qg',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['Eswatini', 'Africa', 'Digital Health Strategy', 'Implementation'],
  },
  {
    id: '26',
    slug: 'regulation-evaluation-digital-health-technologies',
    title: 'What is the right approach for regulation and evaluation of digital health technologies?',
    description: 'A critical look at how digital health technologies should be regulated and evaluated,balancing innovation with safety, and speed with rigour, particularly in low- and middle-income country contexts.',
    youtubeVideoId: 'c1hN-Eo11_U',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['Regulation', 'Evaluation', 'Policy', 'Digital Health', 'LMIC'],
  },
  {
    id: '27',
    slug: 'creating-impact-ai-isolated-communities',
    title: 'Creating impact with AI in isolated communities',
    description: 'How AI tools are being designed and deployed to reach communities with limited connectivity and infrastructure,and what it takes to make impact real rather than theoretical in these contexts.',
    youtubeVideoId: 'vQry1obBOTM',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['AI', 'Last Mile', 'Digital Health', 'Isolated Communities'],
  },
  {
    id: '28',
    slug: 'bridging-the-gap-last-mile-bilal-mateen',
    title: 'Bridging the Gap: The Last Mile of Healthcare with Bilal Mateen, Digital Square @ PATH',
    description: 'Bilal Mateen of Digital Square at PATH on the persistent challenge of reaching the last mile in healthcare,what the data shows, what the evidence supports, and where the biggest leverage points lie.',
    youtubeVideoId: 'KO4aJFs3Xgs',
    date: 'Apr 2025',
    category: 'talk',
    tags: ['Last Mile', 'Digital Square', 'PATH', 'Global Health', 'Implementation'],
  },
  {
    id: '29',
    slug: 'trailer',
    title: 'Trailer: Global Perspectives on Digital Health Podcast',
    description: 'An introduction to the Global Perspectives on Digital Health podcast,who it is for, what it covers, and why these conversations matter.',
    youtubeVideoId: 'ABmm7iO9sDc',
    thumbnailUrl: '/shubs.webp',
    thumbnailPosition: 'center 20%',
    date: 'Apr 2025',
    category: 'clip',
    tags: ['Trailer', 'GPODH'],
  },
  {
    id: '30',
    slug: 'health-data-poverty-part-1-xiao-liu',
    title: 'Health Data Poverty (Part 1) with Dr Xiao Liu',
    description: 'Dr Xiao Liu on the concept of health data poverty,why the systematic under-representation of low- and middle-income country populations in global health datasets is a structural problem with real consequences for AI and digital health.',
    youtubeVideoId: 'm3Lo9BaTDY4',
    date: 'Dec 2024',
    category: 'talk',
    tags: ['Health Data', 'Data Poverty', 'AI', 'LMIC', 'Research'],
  },
  {
    id: '31',
    slug: 'health-data-poverty-part-2-alexandre-filho',
    title: 'Health Data Poverty (Part 2) with Professor Alexandre Filho',
    description: 'Professor Alexandre Filho continues the health data poverty conversation,exploring the structural causes, the geopolitical dimensions, and what it would take to build genuinely representative global health data infrastructure.',
    youtubeVideoId: 'wybLXbexcJM',
    date: 'Dec 2024',
    category: 'talk',
    tags: ['Health Data', 'Data Poverty', 'AI', 'LMIC', 'Research'],
  },
]

export const CATEGORY_LABELS: Record<VideoCategory, string> = {
  talk:      'Talk',
  panel:     'Panel',
  explainer: 'Explainer',
  clip:      'Clip',
}
